#指定服务名字，这个名称将在服务消费者时被调用
spring:
  application:
    name: 03-provider
#指定eureka的访问地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka9100:9100/eureka,http://eureka9200:9200/eureka
#指定tomcat的端口号需要避免和其他tomcat冲突
server:
  port: 8081
